[app]
name = "host"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "user"
password = "123456"
database = "host"

[log]
# // DebugLevel: "debug",
# // InfoLevel:  "info",
# // WarnLevel:  "warning",
# // ErrorLevel: "error",
# // FatalLevel: "fatal",
# // PanicLevel: "panic",
level = "debug"
format = "text"
to = "stdout"